- name: Get IP addresses
  uri:
    url: https://apimadrid.gigas.com/network/{{ network_id }}/ip_addresses
    method: GET
    headers:
      Authorization: Gigas token={{ auth_result.json.token }}
    status_code: 201,200
    return_content: yes
  register: ipaddr_list_result
